system_prompt: |-
  你是一个手机 GUI-Agent 操作专家，你需要根据用户下发的任务、手机屏幕截图和交互操作的历史记录，借助既定的动作空间与手机进行交互，从而完成用户的任务。
  请牢记，手机屏幕坐标系以左上角为原点，x轴向右，y轴向下，取值范围均为 0-1000。

  # 行动原则：

  1. 你需要明确记录自己上一次的action，如果是滑动，不能超过5次。
  2. 你需要严格遵循用户的指令，如果你和用户进行过对话，需要更遵守最后一轮的指令
  3. 重复的action不能超过3次。

  # Action Space:

  在 Android 手机的场景下，你的动作空间包含以下9类操作，所有输出都必须遵守对应的参数要求：
  1. CLICK：点击手机屏幕坐标，需包含点击的坐标位置 point。
  例如：action:CLICK\tpoint:x,y
  2. TYPE：在手机输入框中输入文字，需包含输入内容 value、输入框的位置 point。
  例如：action:TYPE\tvalue:输入内容\tpoint:x,y
  3. COMPLETE：任务完成后向用户报告结果，需包含报告的内容 value。
  例如：action:COMPLETE\treturn:完成任务后向用户报告的内容
  4. WAIT：等待指定时长，需包含等待时间 value（秒）。
  例如：action:WAIT\tvalue:等待时间
  5. AWAKE：唤醒指定应用，需包含唤醒的应用名称 value。
  例如：action:AWAKE\tvalue:应用名称
  6. INFO：询问用户问题或详细信息，需包含提问内容 value。
  例如：action:INFO\tvalue:提问内容
  7. ABORT：终止当前任务，仅在当前任务无法继续执行时使用，需包含 value 说明原因。
  例如：action:ABORT\tvalue:终止任务的原因
  8. SLIDE：在手机屏幕上滑动，滑动的方向不限，需包含起点 point1 和终点 point2。
  例如：action:SLIDE\tpoint1:x1,y1\tpoint2:x2,y2
  9. LONGPRESS：长按手机屏幕坐标，需包含长按的坐标位置 point。
  例如：action:LONGPRESS\tpoint:x,y

model_config:
  vllm:
    api_base: "http://10.233.42.111:8010/v1"
    api_key: "EMPTY"

mirror_display_switch: True

rollout_config:
  model_config:
    model_name: gelab-zero-4b-preview
    model_provider: vllm
    args:
      temperature: 0.1
      top_p: 0.95
      frequency_penalty: 0.0
      max_tokens: 4096
  max_steps: 400
  delay_after_capture: 2
  debug: False

mcp_server_config:
  agent_loop_config: {
    # the gui agent protocol, e.g., parser_0922_summary
    "task_type": "parser_0922_summary",

    # the gui main model config
    "model_config": {
      "model_name": "gelab-zero-4b-preview",
      "model_provider": "vllm",

      "args": {
        "temperature": 0.1,
        "top_p": 0.95,
        "frequency_penalty": 0.0,
        "max_tokens": 4096,
      },
      
      # optional to resize image
      "image_preprocess": {
        "is_resize": True,
        "target_image_size": [728, 728]
      }
    },

    # the maximum steps for the agent loop
    "max_steps": 400,

    # the delay time after each action to next capture screenshot
    "delay_after_capture": 2,

    # debug mode if True will print more logs
    "debug": False,

    # reply_config:
    # optional, the config for auto reply with llm
    # if auto reply is enabled in the agent loop, if this config is not provided,
    # the main model_config will be used for auto reply
    # if provided, will use this config for auto reply
    "reply_config": {
      "model_config": {
        "model_name": "gelab-zero-4b-preview",
        "model_provider": "vllm",

        "args": {
          "temperature": 0.5,
          "top_p": 0.95,
          "frequency_penalty": 0.0,
          "max_tokens": 512,
        },

        # optional to resize image
        "image_preprocess": {
          "is_resize": True,
          "target_image_size": [728, 728]
        }
      }
    },

    # caption config: 
    # optional, the config for image captioning
    # if image captioning is enabled in the agent loop, this config will be used
    # to caption the image before sending to the model
    "caption_config": {
      "model_config": {
        "model_name": "gelab-zero-4b-preview",
        "model_provider": "vllm",

        "args": {
          "temperature": 0.5,
          "top_p": 0.95,
          "frequency_penalty": 0.0,
          "max_tokens": 512,
        },

        # optional to resize image
        "image_preprocess": {
          "is_resize": True,
          "target_image_size": [728, 728]
        }
      }
    },

  }

  server_config : {
    "mcp_server_port": 8704,
    "log_dir": "running_log/server_log/os-copilot-local-eval-logs/traces",
    "image_dir": "running_log/server_log/os-copilot-local-eval-logs/images",
    "debug": False
  }
