local:
    api_base: "http://localhost:11434/v1"
    api_key: "EMPTY"

stepfun:
    api_base: "https://api.stepfun.com/v1"
    api_key: "EMPTY"

vllm:
    api_base: "http://10.233.42.111:8010/v1"
    api_key: "EMPTY"